#!/bin/sh

. /etc/os-release

BUILD=$(opkg list-installed omega2-base | awk -F- '{print $NF}')
uci import onion < /dev/null

uci -q batch <<-EOF > /dev/null
	set onion.onion='onion'
	set onion.onion.version=${VERSION_ID}
	set onion.onion.build="${BUILD:-1}"

	commit onion
EOF

exit 0
