#!/bin/sh

mv /etc/banner /etc/banner_tmp

# add Omega ascii art
OMEGA="   ____       _             ____
  / __ \\___  (_)__  ___    / __ \\__ _  ___ ___ ____ _
 / /_/ / _ \\/ / _ \\/ _ \\  / /_/ /  ' \\/ -_) _ \`/ _ \`/
 \\____/_//_/_/\\___/_//_/  \\____/_/_/_/\\__/\\_, /\\_,_/
 W H A T  W I L L  Y O U  I N V E N T ?  /___/"

echo "$OMEGA" > /etc/banner

# add Omega firmware version
version=$(uci get onion.@onion[0].version)
build=$(uci get onion.@onion[0].build)
echo " ----------------------------------------------------- " >> /etc/banner
echo "               Ω-ware:  $version $build                " >> /etc/banner
echo " ----------------------------------------------------- " >> /etc/banner
echo "   This is new firmware! For more info," >> /etc/banner
echo "   visit https://documentation.onioniot.com" >> /etc/banner
echo " -----------------------------------------------------" >> /etc/banner

rm /etc/banner_tmp

