#!/bin/sh

MAC_ID=$(cat /sys/class/net/wlan0/address | tr -d ':' | tail -c5 | tr '[a-z]' '[A-Z]')
HOSTNAME="Omega-${MAC_ID}"

uci -q batch <<-EOF > /dev/null
	set network.lan.ipaddr='192.168.4.1'

	del_list network.@device[0].ports='eth0'
	set network.wan='interface'
	set network.wan.proto='dhcp'
	set network.wan.device='eth0'
	set network.wan.hostname="${HOSTNAME}"

	set network.wlan='interface'
	set network.wlan.device='ra0'
	set network.wlan.proto='static'
	set network.wlan.ipaddr='192.168.3.1'
	set network.wlan.netmask='255.255.255.0'
	set network.wlan.ip6assign='60'

	set network.wwan='interface'
	set network.wwan.proto='dhcp'
	set network.wwan.device='apcli0'
	set network.wwan.hostname="${HOSTNAME}"

	commit network

	set wireless.@wifi-device[0].disabled='0'
	set wireless.@wifi-device[0].channel='auto'
	set wireless.@wifi-device[0].htmode='HT40'
	set wireless.@wifi-iface[0].ifname='ra0'
	set wireless.@wifi-iface[0].network='wlan'
	set wireless.@wifi-iface[0].ssid="${HOSTNAME}"
	set wireless.@wifi-iface[0].encryption='psk2'
	set wireless.@wifi-iface[0].key='12345678'

	set wireless.client=wifi-iface
	set wireless.client.device='radio0'
	set wireless.client.network='wwan'
	set wireless.client.mode='sta'
	set wireless.client.ssid=MySSID
 	set wireless.client.key=MyKey
	set wireless.client.encryption=psk2
	set wireless.client.ifname=apcli0
	set wireless.client.disabled=1

	commit wireless

	add_list firewall.@zone[0].network='wlan'

	del_list firewall.@zone[1].network='wan6'
	add_list firewall.@zone[1].network='wwan'
	set firewall.@zone[1].mtu_fix='1'
	set firewall.@zone[1].input='ACCEPT'
	set firewall.@zone[1].forward='ACCEPT'

	commit firewall

	set dhcp.wlan='dhcp'
	set dhcp.wlan.interface='wlan'
	set dhcp.wlan.start='100'
	set dhcp.wlan.limit='150'
	set dhcp.wlan.leasetime='12h'
	set dhcp.wlan.dhcpv4='server'
	set dhcp.wlan.dhcpv6='server'
	set dhcp.wlan.ra='server'
	set dhcp.wlan.ra_slaac='1'
	add_list dhcp.wlan.ra_flags='managed-config'
	add_list dhcp.wlan.ra_flags='other-config'
	commit dhcp
EOF

exit 0
