# This file is not used: for reference only
#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: MIT-0
version: 0.2
env:
  variables:
    VERSION: "22.03.2"
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Installing dependencies"
      - apt-get update
      - apt-get -y install --upgrade awscli
      - apt-get -y install build-essential libncurses5-dev libncursesw5-dev zlib1g-dev gawk git gettext libssl-dev xsltproc rsync wget unzip python2
  pre_build:
    commands:
      - aws s3 cp s3://onion-build/openwrt/openwrt21.key $CODEBUILD_SRC_DIR/keys/key-build
      - aws s3 cp s3://onion-build/openwrt/openwrt21.pub $CODEBUILD_SRC_DIR/keys/key-build.pub
      - cd $CODEBUILD_SRC_DIR
      - bash setup.sh
  build:
    commands:
      - bash build-packages.sh
  post_build:
    commands:
      - if [ "$CODEBUILD_BUILD_SUCCEEDING" = "0" ]; then exit 1; fi
      - cd "openwrt-sdk-$VERSION/bin/packages/mipsel_24kc/onion"
      - aws s3 cp --recursive . "s3://repo.onioniot.com/omega2/packages/openwrt-$VERSION/onion"
cache:
  paths:
    - /var/cache/apt/**/*
    - /var/lib/apt/lists/**/*

artifacts:
  type: zip
  files: "**/*"
  base-directory: "openwrt-sdk-$VERSION/bin/packages/mipsel_24kc/onion"
