#!/bin/sh /etc/rc.common
# Copyright (C) 2010 OpenWrt.org

# enable auto start of this daemon
START=99

USE_PROCD=1
PROG=/usr/sbin/shellinaboxd

start_service() {
        procd_open_instance
        procd_set_param command $PROG -t --service=/:LOGIN --css /usr/lib/shellinabox/style.css
        # disable automatic respawn - allow daemon to be turned off
	#procd_set_param respawn                                                                   
        procd_close_instance   
}
 
