name: Release to production
on:
  release:
    types: [published]
permissions: write-all
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: push to release branch
        run: git push -f origin "HEAD:refs/heads/release"